root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/scene-server main.go"
  full_bin = "bash -c 'set -a; source ../.env 2>/dev/null || true; set +a; ./tmp/scene-server -port 8081'"
  delay = 1000
  exclude_dir = ["tmp", "static"]
  exclude_regex = ["_test.go"]
  include_ext = ["go", "html", "js", "css"]
  kill_delay = "0s"
  log = "build-errors.log"
  rerun_delay = 500

[color]
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  time = false

[misc]
  clean_on_exit = false

[screen]
  clear_on_rebuild = false
  keep_scroll = true